/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiResolveRouteImport } from './routes/api/resolve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveRoute = ApiResolveRouteImport.update({
  id: '/api/resolve',
  path: '/api/resolve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/resolve': typeof ApiResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/resolve': typeof ApiResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/media': typeof ApiMediaRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/resolve': typeof ApiResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/media' | '/api/profile' | '/api/resolve'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/media' | '/api/profile' | '/api/resolve'
  id: '__root__' | '/' | '/api/media' | '/api/profile' | '/api/resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiResolveRoute: typeof ApiResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve': {
      id: '/api/resolve'
      path: '/api/resolve'
      fullPath: '/api/resolve'
      preLoaderRoute: typeof ApiResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiResolveRoute: ApiResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
